-- goal 的执行结果，用于 update
GOAL_RESULT_Failed = -1
GOAL_RESULT_Continue = 0
GOAL_RESULT_Success = 1

-- 方向，以 self 为参照
AI_DIR_TYPE_CENTER = 0
AI_DIR_TYPE_F = 1
AI_DIR_TYPE_B = 2
AI_DIR_TYPE_L = 3
AI_DIR_TYPE_R = 4
AI_DIR_TYPE_ToF = 5
AI_DIR_TYPE_ToB = 6
AI_DIR_TYPE_ToL = 7
AI_DIR_TYPE_ToR = 8
AI_DIR_TYPE_Top = 9

AI_SPA_DIR_TYPE_TargetF = 0
AI_SPA_DIR_TYPE_ToTarget = 1
AI_SPA_DIR_TYPE_Absolute = 2

-- 距离大小，用于 goal attack 参数
DIST_Near = -1
DIST_Middle = -2
DIST_Far = -3
DIST_Out = -4
DIST_None = -5

-- 当前仇恨目标
TARGET_NONE = -2
-- 没有仇恨？
TARGET_SELF = -1
-- 通常为 pc
TARGET_ENE_0 = 0
TARGET_FRI_0 = 10
TARGET_EVENT = 20
TARGET_LOCALPLAYER = 21
TARGET_LowHp_Friend = 22
TARGET_INTERMEDIATE_POINT = 23
TARGET_TEAM_FORMATION = 24
TARGET_TEAM_LEADER = 25
TARGET_MEMORIED_RELATIVE_TARGET = 26
TARGET_ENEMY_AVATOR_HOME = 50
TARGET_PERSONAL_AVATOR_HOME = 51
TARGET_TYPE_BOIDS_COMMAND = 60

POINT_INITIAL = 100
POINT_SNIPE = 101
POINT_EVENT = 102
POINT_MOVE_POINT = 103
POINT_NEAR_NAVIMESH = 104
POINT_FAR_NAVIGATE = 105
POINT_NEAR_NAVIGATE = 106
POINT_AI_FIXED_POS = 107
POINT_FAR_LANDING = 108
POINT_NEAR_LANDING = 109
POINT_2ndNEAR_LANDING = 110
POINT_INIT_POSE = 111
POINT_HitObstacle = 112
POINT_CurrRequestPosition = 114
POINT_NearMovePoint = 115
POINT_NEAR_OBJ_ACT_POINT = 116
POINT_2ndNEAR_OBJ_ACT_POINT = 117
POINT_LastSightPosition = 118
POINT_AutoWalkAroundTest = 120
POINT_WalkAroundPosition_Home = 121
POINT_UnstableFloor_CausePos = 122
POINT_WalkAroundPosition_Free = 123
POINT_AIPredictionTargetPos = 124
POINT_BackToHome = 125
POINT_UnreachTerminate = 126

-- 引发变招的方式类别
-- 占位符，用于 for loop
INTERUPT_First = 0
-- 发现敌人？
INTERUPT_FindEnemy = 0
-- 发现攻击？
INTERUPT_FindAttack = 1
-- 
INTERUPT_Damaged = 2
-- 
INTERUPT_Damaged_Stranger = 3
INTERUPT_FindMissile = 4
INTERUPT_SuccessGuard = 5
INTERUPT_MissSwing = 6
INTERUPT_GuardBegin = 7
INTERUPT_GuardFinish = 8
INTERUPT_GuardBreak = 9
INTERUPT_Shoot = 10
-- 被pc的远程攻击打断
INTERUPT_ShootImpact = 11
-- 对 pc 的药检
INTERUPT_UseItem = 12
INTERUPT_EnterBattleArea = 13
INTERUPT_LeaveBattleArea = 14
INTERUPT_CANNOT_MOVE = 15
INTERUPT_Inside_ObserveArea = 16
INTERUPT_ReboundByOpponentGuard = 17
INTERUPT_ForgetTarget = 18
INTERUPT_FriendRequestSupport = 19
INTERUPT_TargetIsGuard = 20
INTERUPT_HitEnemyWall = 21
-- 成功弹开
INTERUPT_SuccessParry = 22
INTERUPT_CANNOT_MOVE_DisableInterupt = 23
-- pc 的攻击信号
INTERUPT_ParryTiming = 24
INTERUPT_RideNode_LadderBottom = 25
INTERUPT_FLAG_RideNode_Door = 26
INTERUPT_StraightByPath = 27
INTERUPT_ChangedAnimIdOffset = 28
INTERUPT_SuccessThrow = 29
INTERUPT_LookedTarget = 30
-- pc 消失在视界外
INTERUPT_LoseSightTarget = 31
INTERUPT_RideNode_InsideWall = 32
INTERUPT_MissSwingSelf = 33
INTERUPT_GuardBreakBlow = 34
-- pc 在范围外
INTERUPT_TargetOutOfRange = 35
INTERUPT_UnstableFloor = 36
INTERUPT_BreakFloor = 37
INTERUPT_BreakObserveObj = 38
-- 被事件中断
INTERUPT_EventRequest = 39
-- 离开观测区域
INTERUPT_Outside_ObserveArea = 40
-- pc 在角度外？？？
INTERUPT_TargetOutOfAngle = 41
INTERUPT_PlatoonAiOrder = 42
-- 被观察的 sp 中断
INTERUPT_ActivateSpecialEffect = 43
INTERUPT_InactivateSpecialEffect = 44
--
INTERUPT_MovedEnd_OnFailedPath = 45
INTERUPT_ChangeSoundTarget = 46
INTERUPT_OnCreateDamage = 47
INTERUPT_InvadeTriggerRegion = 48
INTERUPT_LeaveTriggerRegion = 49
INTERUPT_AIGuardBroken = 50
INTERUPT_AIReboundByOpponentGuard = 51
INTERUPT_BackstabRisk = 52
INTERUPT_FindIndicationTarget = 53
INTERUPT_FindFailedPath = 54
INTERUPT_FindCorpseTarget = 55
INTERUPT_GuardedMyAttack = 56
INTERUPT_WanderedOffPathRepath = 57
INTERUPT_Last = 57

-- 群集 ai？
PLATOON_STATE_None = 0
PLATOON_STATE_Caution = 1
PLATOON_STATE_Find = 2
PLATOON_STATE_ReplyHelp = 3
PLATOON_STATE_Battle = 4

COORDINATE_TYPE_None = -1
COORDINATE_TYPE_Attack = 0
COORDINATE_TYPE_SideWalk_L = 1
COORDINATE_TYPE_SideWalk_R = 2
COORDINATE_TYPE_AttackOrder = 3
COORDINATE_TYPE_Support = 4
COORDINATE_TYPE_KIMERAbite = 100
COORDINATE_TYPE_UROKOIwaSupport = 110

ORDER_TYPE_Role = 0
ORDER_TYPE_CallHelp = 1

ROLE_TYPE_None = -1
ROLE_TYPE_Attack = 0
ROLE_TYPE_Torimaki = 1
ROLE_TYPE_Kankyaku = 2

NPC_ATK_R1 = 0
NPC_ATK_R1_Hold = 1
NPC_ATK_R2 = 2
NPC_ATK_R2_Hold = 3
NPC_ATK_L1 = 4
NPC_ATK_L1Hold = 6
NPC_ATK_L2 = 7
NPC_ATK_L2Hold = 8
NPC_ATK_L3 = 9
NPC_ATK_Up_R1 = 10
NPC_ATK_Up_R2 = 11
NPC_ATK_ButtonTriangle = 12
NPC_ATK_ButtonSquare = 13
NPC_ATK_ButtonCircle = 14
NPC_ATK_ButtonXmark = 15
NPC_ATK_ArrowKeyLeft = 16
NPC_ATK_ArrowKeyRight = 17
NPC_ATK_Up = 18
NPC_ATK_UpLeft = 19
NPC_ATK_UpRight = 20
NPC_ATK_Left = 21
NPC_ATK_Right = 22
NPC_ATK_Down = 23
NPC_ATK_DownLeft = 24
NPC_ATK_DownRight = 25
NPC_ATK_Up_L1Hold = 26
NPC_ATK_UpLeft_L1Hold = 27
NPC_ATK_UpRight_L1Hold = 28
NPC_ATK_Left_L1Hold = 29
NPC_ATK_Right_L1Hold = 30
NPC_ATK_Down_L1Hold = 31
NPC_ATK_DownLeft_L1Hold = 32
NPC_ATK_DownRight_L1Hold = 33
NPC_ATK_UpHold_ButtonXmarkHold = 34
NPC_ATK_UpHold_ButtonXmarkHold_L2Hold = 35
NPC_ATK_Up_ButtonXmark = 36
NPC_ATK_UpLeft_ButtonXmark = 37
NPC_ATK_UpRight_ButtonXmark = 38
NPC_ATK_Left_ButtonXmark = 39
NPC_ATK_Right_ButtonXmark = 40
NPC_ATK_Down_ButtonXmark = 41
NPC_ATK_DownLeft_ButtonXmark = 42
NPC_ATK_DownRight_ButtonXmark = 43
NPC_ATK_L2Hold_R1 = 48
NPC_ATK_L2Hold_R2 = 49
NPC_ATK_Up_L2 = 50
NPC_ATK_UpLeft_L2 = 51
NPC_ATK_UpRight_L2 = 52
NPC_ATK_Left_L2 = 53
NPC_ATK_Right_L2 = 54
NPC_ATK_Down_L2 = 55
NPC_ATK_DownLeft_L2 = 56
NPC_ATK_DownRight_L2 = 57
NPC_ATK_UpHold_L2Hold = 58
NPC_ATK_UpLeftHold_L2Hold = 59
NPC_ATK_UpRightHold_L2Hold = 60
NPC_ATK_LeftHold_L2Hold = 61
NPC_ATK_RightHold_L2Hold = 62
NPC_ATK_DownHold_L2Hold = 63
NPC_ATK_DownLeftHold_L2Hold = 64
NPC_ATK_DownRightHold_L2Hold = 65
NPC_ATK_UpHold_L2Hold_R1 = 66
NPC_ATK_UpLeftHold_L2Hold_R1 = 67
NPC_ATK_UpRightHold_L2Hold_R1 = 68
NPC_ATK_LeftHold_L2Hold_R1 = 69
NPC_ATK_RightHold_L2Hold_R1 = 70
NPC_ATK_DownHold_L2Hold_R1 = 71
NPC_ATK_DownLeftHold_L2Hold_R1 = 72
NPC_ATK_DownRightHold_L2Hold_R1 = 73
NPC_ATK_UpHold_L2Hold_R2 = 74
NPC_ATK_UpLeftHold_L2Hold_R2 = 75
NPC_ATK_UpRightHold_L2Hold_R2 = 76
NPC_ATK_LeftHold_L2Hold_R2 = 77
NPC_ATK_RightHold_L2Hold_R2 = 78
NPC_ATK_DownHold_L2Hold_R2 = 79
NPC_ATK_DownLeftHold_L2Hold_R2 = 80
NPC_ATK_DownRightHold_L2Hold_R2 = 81
NPC_ATK_L1Hold_R1 = 82
NPC_ATK_L1Hold_R2 = 83
NPC_ATK_LadderUp = 90
NPC_ATK_LadderDown = 91
NPC_ATK_Gesture00 = 100
NPC_ATK_Gesture01 = 101
NPC_ATK_Gesture02 = 102
NPC_ATK_Gesture03 = 103
NPC_ATK_Gesture04 = 104
NPC_ATK_Gesture05 = 105
NPC_ATK_Gesture06 = 106
NPC_ATK_Gesture07 = 107
NPC_ATK_Gesture08 = 108
NPC_ATK_Gesture09 = 109
NPC_ATK_Gesture10 = 110
NPC_ATK_Gesture11 = 111
NPC_ATK_Gesture12 = 112
NPC_ATK_Gesture13 = 113
NPC_ATK_Gesture14 = 114
NPC_ATK_Gesture15 = 115
NPC_ATK_Gesture16 = 116
NPC_ATK_Gesture17 = 117
NPC_ATK_Gesture18 = 118
NPC_ATK_Gesture19 = 119
NPC_ATK_Gesture20 = 120
NPC_ATK_Gesture21 = 121
NPC_ATK_Gesture22 = 122
NPC_ATK_Gesture23 = 123
NPC_ATK_Gesture24 = 124
NPC_ATK_Gesture25 = 125
NPC_ATK_Gesture26 = 126
NPC_ATK_Gesture27 = 127
NPC_ATK_Gesture28 = 128
NPC_ATK_Gesture29 = 129
NPC_ATK_Gesture30 = 130
NPC_ATK_Gesture31 = 131
NPC_ATK_Gesture32 = 132
NPC_ATK_Gesture33 = 133
NPC_ATK_Gesture34 = 134
NPC_ATK_Gesture35 = 135
NPC_ATK_Gesture36 = 136
NPC_ATK_Gesture37 = 137
NPC_ATK_Gesture38 = 138
NPC_ATK_Gesture39 = 139
NPC_ATK_Gesture40 = 140
NPC_ATK_NormalR = 0
NPC_ATK_LargeR = 1
NPC_ATK_PushR = 2
NPC_ATK_NormalL = 3
NPC_ATK_GuardL = 4
NPC_ATK_Parry = 5
NPC_ATK_Magic = 6
NPC_ATK_MagicL = NPC_ATK_Magic
NPC_ATK_Item = 7
NPC_ATK_SwitchWep = 8
NPC_ATK_StepF = 9
NPC_ATK_StepB = 10
NPC_ATK_StepL = 11
NPC_ATK_StepR = 12
NPC_ATK_ChangeWep_R1 = 13
NPC_ATK_ChangeWep_R2 = 14
NPC_ATK_ChangeWep_L1 = 15
NPC_ATK_ChangeWep_L2 = 16
NPC_ATK_BackstepF = 17
NPC_ATK_BackstepB = 18
NPC_ATK_BackstepL = 19
NPC_ATK_BackstepR = 20
NPC_ATK_MagicR = 21

AI_EXCEL_THINK_PARAM_TYPE__NONE = 0
AI_EXCEL_THINK_PARAM_TYPE__maxBackhomeDist = 1
AI_EXCEL_THINK_PARAM_TYPE__backhomeDist = 2
AI_EXCEL_THINK_PARAM_TYPE__backhomeBattleDist = 3
AI_EXCEL_THINK_PARAM_TYPE__nonBattleActLife = 4
AI_EXCEL_THINK_PARAM_TYPE__BattleStartDist = 5
AI_EXCEL_THINK_PARAM_TYPE__bMoveOnHearSound = 6
AI_EXCEL_THINK_PARAM_TYPE__CannotMoveAction = 7
AI_EXCEL_THINK_PARAM_TYPE__battleGoalID = 8
AI_EXCEL_THINK_PARAM_TYPE__BackHome_LookTargetTime = 9
AI_EXCEL_THINK_PARAM_TYPE__BackHome_LookTargetDist = 10
AI_EXCEL_THINK_PARAM_TYPE__BackHomeLife_OnHitEnemyWall = 11
AI_EXCEL_THINK_PARAM_TYPE__callHelp_IsCall = 12
AI_EXCEL_THINK_PARAM_TYPE__callHelp_IsReply = 13
AI_EXCEL_THINK_PARAM_TYPE__callHelp_MyPeerId = 14
AI_EXCEL_THINK_PARAM_TYPE__callHelp_CallPeerId = 15
AI_EXCEL_THINK_PARAM_TYPE__callHelp_DelayTime = 16
AI_EXCEL_THINK_PARAM_TYPE__callHelp_CallActionId = 17
AI_EXCEL_THINK_PARAM_TYPE__callHelp_ReplyBehaviorType = 18
AI_EXCEL_THINK_PARAM_TYPE__callHelp_ForgetTimeByArrival = 19
AI_EXCEL_THINK_PARAM_TYPE__callHelp_MinWaitTime = 20
AI_EXCEL_THINK_PARAM_TYPE__callHelp_MaxWaitTime = 21
AI_EXCEL_THINK_PARAM_TYPE__callHelp_ReplyActionId = 22
AI_EXCEL_THINK_PARAM_TYPE__thinkAttr_doAdmirer = 23
AI_EXCEL_THINK_PARAM_TYPE__goalAction_ToDisappear = 24
AI_EXCEL_THINK_PARAM_TYPE__goalAction_ToCaution = 25
AI_EXCEL_THINK_PARAM_TYPE__goalAction_ToCautionImportant = 26
AI_EXCEL_THINK_PARAM_TYPE__goalAction_ToFind = 27
AI_EXCEL_THINK_PARAM_TYPE__changeStateAction_ToNormal = 28
AI_EXCEL_THINK_PARAM_TYPE__goalAction_ToCautionIndicationTarget = 29
AI_EXCEL_THINK_PARAM_TYPE__goalAction_ToCautionCorpseTarget = 30

POINT_MOVE_TYPE_Patrol = 0
POINT_MOVE_TYPE_RoundTrip = 1
POINT_MOVE_TYPE_Randum = 2
POINT_MOVE_TYPE_Gargoyle_Air_Patrol = 3
POINT_MOVE_TYPE_Gargoyle_Landing = 4

ARM_L = 0
ARM_R = 1

WEP_Primary = 0
WEP_Secondary = 1

PARTS_DMG_NONE = 0
PARTS_DMG_LV1 = 1
PARTS_DMG_LV2 = 2
PARTS_DMG_LV3 = 3
PARTS_DMG_FINAL = 20

SP_EFFECT_TYPE_NONE = 0
SP_EFFECT_TYPE_FIRE = 1
SP_EFFECT_TYPE_POIZON = 2
SP_EFFECT_TYPE_LEECH = 3
SP_EFFECT_TYPE_SPOIL = 4
SP_EFFECT_TYPE_ILLNESS = 5
SP_EFFECT_TYPE_BLOOD = 6
SP_EFFECT_TYPE_CAMOUFLAGE = 7
SP_EFFECT_TYPE_HIDDEN = 8
SP_EFFECT_TYPE_MASOCHIST = 9
SP_EFFECT_TYPE_RECOVER_POZON = 10
SP_EFFECT_TYPE_RECOVER_ILLNESS = 11
SP_EFFECT_TYPE_RECOVER_BLOOD = 12
SP_EFFECT_TYPE_RECOVER_ALL = 13
SP_EFFECT_TYPE_SOUL_STEAL = 14
SP_EFFECT_TYPE_ZOOM = 15
SP_EFFECT_TYPE_WARP = 16
SP_EFFECT_TYPE_DEMONS_SOUL = 17
SP_EFFECT_TYPE_BLACK_DISPERSE = 18
SP_EFFECT_TYPE_TOUGH_GHOST = 19
SP_EFFECT_TYPE_WHITE_REQUEST = 20
SP_EFFECT_TYPE_BLACK_REQUEST = 21
SP_EFFECT_TYPE_CHANGE_BLACK = 22
SP_EFFECT_TYPE_REVIVE = 23
SP_EFFECT_TYPE_FORBID_USEMAGIC = 24
SP_EFFECT_TYPE_MIRACLE_DIRAY = 25
SP_EFFECT_TYPE_WHETSTONE = 26
SP_EFFECT_TYPE_SUSPENDED_REVIVE = 27
SP_EFFECT_TYPE_ENCHANT_WEAPON = 28
SP_EFFECT_TYPE_ENCHANT_ARMOR = 29
SP_EFFECT_TYPE_WIRE_WRAPED = 30
SP_EFFECT_TYPE_GHOST_PARAM_CHANGE = 31
SP_EFFECT_TYPE_PARALYSIS = 32
SP_EFFECT_TYPE_FLY_CROWD = 33
SP_EFFECT_TYPE_FIREMAN_STAGE_1 = 34
SP_EFFECT_TYPE_FIREMAN_STAGE_2 = 35
SP_EFFECT_TYPE_FIREMAN_STAGE_3 = 36
SP_EFFECT_TYPE_FIREMAN_STAGE_4 = 37
SP_EFFECT_TYPE_HALLUCINATION = 38
SP_EFFECT_TYPE_SOULCOIN = 39
SP_EFFECT_TYPE_TOUGH_SHIELD = 40
SP_EFFECT_TYPE_ANTIFIRE_SHIELD = 41
SP_EFFECT_TYPE_HP_RECOVERY = 42
SP_EFFECT_TYPE_FORCE_GHOST_STAGE1 = 43
SP_EFFECT_TYPE_FORCE_GHOST_STAGE2 = 44
SP_EFFECT_TYPE_FORCE_GHOST_STAGE3 = 45
SP_EFFECT_TYPE_PHEROMONE = 46
SP_EFFECT_TYPE_CAT_LANDING = 47
SP_EFFECT_TYPE_PINCH_ATTACKPOWER_UP = 48
SP_EFFECT_TYPE_PINCH_DEFENSIBILITY_UP = 49
SP_EFFECT_TYPE_REGENERATE = 50
SP_EFFECT_TYPE_TORCH = 51
SP_EFFECT_TYPE_WEAK_REGENERATE = 52
SP_EFFECT_TYPE_WEAK_CAMOUFLAGE = 53
SP_EFFECT_TYPE_WEAK_HIDDEN = 54
SP_EFFECT_TYPE_HINT_BLOOD_SIGN = 55
SP_EFFECT_TYPE_LEECH_FOOT = 56
SP_EFFECT_TYPE_YELLOW_CLOAK = 57
SP_EFFECT_TYPE_POINT_LIGHT = 58
SP_EFFECT_TYPE_BLOOD_SIGN_ESTIMATION = 59
SP_EFFECT_TYPE_ENCHANT_WEAPON_REGULAR = 60
SP_EFFECT_TYPE_ENCHANT_WEAPON_LARGE = 61
SP_EFFECT_TYPE_ENCHANT_WEAPON_FIRE = 62
SP_EFFECT_TYPE_ENCHANT_WEAPON_FIRE_LARGE = 63
SP_EFFECT_TYPE_ENCHANT_WEAPON_MAGIC = 64
SP_EFFECT_TYPE_CHIMERA_POWER_UP = 65
SP_EFFECT_TYPE_ITEM_DROP_RATE = 66
SP_EFFECT_TYPE_TARGET_DOWN = 259

OBJ_ACT_TYPE_LEVER = 0
OBJ_ACT_TYPE_DOOR = 1

TEAM_TYPE_None = 0
TEAM_TYPE_Host = 19
TEAM_TYPE_Coop = 20
TEAM_TYPE_Oppose = 21
TEAM_TYPE_Phantom = 22
TEAM_TYPE_Enemy1 = 23
TEAM_TYPE_Enemy2 = 24
TEAM_TYPE_Archenemy = 25
TEAM_TYPE_SupportNpc = 26
TEAM_TYPE_OpposeNpc = 27
TEAM_TYPE_JointNpc = 28
TEAM_TYPE_Indiscriminate = 29
TEAM_TYPE_Obj = 30
TEAM_TYPE_WhiteBerserker = 31
TEAM_TYPE_RedBerserker = 32
TEAM_TYPE_ArchenemyTeam = 33

GUARD_GOAL_DESIRE_RET_Success = 1
GUARD_GOAL_DESIRE_RET_Continue = 2
GUARD_GOAL_DESIRE_RET_Failed = 3

WEP_CATE_None = 0
WEP_CATE_Shield = 1
WEP_CATE_Bow = 2
WEP_CATE_Crossbow = 3
WEP_CATE_Wand = 4

AI_LIST_ROW_TYPE__NEAR_TARGET = 0
AI_AREAOBSERVE_INTERRUPT__NOCHANGE = 0
AI_AREAOBSERVE_INTERRUPT__INSIDE = 1
AI_AREAOBSERVE_INTERRUPT__OUTSIDE = 2
AI_GOAL_FAILED_END_OPT__replanning = 0
AI_GOAL_FAILED_END_OPT__PARENT_NEXT_SUB_GOAL = 1

TARGET_ANGLE_FRONT = 0
TARGET_ANGLE_RIGHT = 1
TARGET_ANGLE_LEFT = 2
TARGET_ANGLE_BACK = 3

WEAPON_CHANGE_1 = 0
WEAPON_CHANGE_2 = 1
WEAPON_CHANGE_3 = 2
WEAPON_CHANGE_4 = 3

GET_MESH_HEIGHT_ERROR = 99999

AI_ATTACK_PARAM_TYPE__SUCCESS_DISTANCE = 0
AI_ATTACK_PARAM_TYPE__TURN_TIME_BEFORE_ATTACK = 1
AI_ATTACK_PARAM_TYPE__FRONT_ANGLE_RANGE = 2
AI_ATTACK_PARAM_TYPE__UP_ANGLE_THRESHOLD = 3
AI_ATTACK_PARAM_TYPE__DOWN_ANGLE_THRESHOLD = 4
AI_ATTACK_PARAM_TYPE__MIN_OPTIMAL_DISTANCE = 5
AI_ATTACK_PARAM_TYPE__MAX_OPTIMAL_DISTANCE = 6
AI_ATTACK_PARAM_TYPE__BASE_DIR_FOR_OPTIMAL_ANGLE_1 = 7
AI_ATTACK_PARAM_TYPE__OPTIMAL_ATTACK_ANGLE_RANGE_1 = 8
AI_ATTACK_PARAM_TYPE__BASE_DIR_FOR_OPTIMAL_ANGLE_2 = 9
AI_ATTACK_PARAM_TYPE__OPTIMAL_ATTACK_ANGLE_RANGE_2 = 10
AI_ATTACK_PARAM_TYPE__INTERVAL_EXEC = 11
AI_ATTACK_PARAM_TYPE__SELECTION_TENDENCY = 12
AI_ATTACK_PARAM_TYPE__IS_FIRST_ATTACK = 13
AI_ATTACK_PARAM_TYPE__SHORT_RANGE_TENDENCY = 14
AI_ATTACK_PARAM_TYPE__MIDDLE_RANGE_TENDENCY = 15
AI_ATTACK_PARAM_TYPE__FAR_RANGE_TENDENCY = 16
AI_ATTACK_PARAM_TYPE__OUT_RANGE_TENDENCY = 17
AI_ATTACK_PARAM_TYPE__DOES_SELECT_ON_OUT_RANGE = 18
AI_ATTACK_PARAM_TYPE__MIN_GOAL_LIFE = 19
AI_ATTACK_PARAM_TYPE__MAX_GOAL_LIFE = 20
AI_ATTACK_PARAM_TYPE__DOES_SELECT_ON_INNER_RANGE = 21
AI_ATTACK_PARAM_TYPE__IS_SELECTABLE_ON_BATTLE_START = 22
AI_ATTACK_PARAM_TYPE__DOES_SELECT_ON_TARGET_DOWN = 23
AI_ATTACK_PARAM_TYPE__MIN_ARRIVE_DISTANCE = 24
AI_ATTACK_PARAM_TYPE__MAX_ARRIVE_DISTANCE = 25
AI_ATTACK_PARAM_TYPE__COMBO_EXEC_DISTANCE = 26
AI_ATTACK_PARAM_TYPE__COMBO_EXEC_RANGE = 27

AI_SOUND_RANK__NORMAL = 0
AI_SOUND_RANK__IMPORTANT = 1

AI_ATK_DIR_FRONT = 0
AI_ATK_DIR_UP = 1
AI_ATK_DIR_DOWN = 2
AI_ATK_DIR_LEFT = 3
AI_ATK_DIR_RIGHT = 4

AI_CALC_DIST_TYPE__XYZ = 0
AI_CALC_DIST_TYPE__XZ = 1

-- goal 执行的时机
-- activate 时
AI_TIMING_SET__ACTIVATE = 0
-- update succeess 时
AI_TIMING_SET__UPDATE_SUCCESS = 1

AI_TARGET_STATE__NONE = 0
AI_TARGET_STATE__CAUTION = 1
AI_TARGET_STATE__FIND = 2
AI_TARGET_STATE__BATTLE = 3

-- 无
AI_TARGET_TYPE__NONE = 0
-- 正常敌人？
AI_TARGET_TYPE__NORMAL_ENEMY = 3
-- 声响
AI_TARGET_TYPE__SOUND = 4
-- 见过的敌人？
AI_TARGET_TYPE__MEMORY_ENEMY = 5
-- 指示位置？
AI_TARGET_TYPE__INDICATION_POS = 6
-- 守尸相关
AI_TARGET_TYPE__CORPSE_POS = 7


AI_FAILED_PATH_NONBTL_ACT_TYPE__STAY = 0
AI_FAILED_PATH_NONBTL_ACT_TYPE__WALK_AROUND = 1

COMMON_FLAG_EXPERIMENT = 1
COMMON_FLAG_BOSS = 2

PC_ATTACK_DIST_STAND = 3.4
PC_ATTACK_DIST_CROUCH = 4.4
PC_ATTACK_DIST_THRUST = 5.8
PC_ATTACK_DIST_TESSEN = 2.5
PC_ATTACK_DIST_AXE = 3.3
PC_ATTACK_DIST_KODACHI = 3.8
PC_ATTACK_DIST_LANCE_1 = 7.03
PC_ATTACK_DIST_LANCE_2 = 5.39
PC_ATTACK_DIST_LANCE_1_LV2 = 7.42
PC_ATTACK_DIST_LANCE_TYPE1_CHARGE = 11.61
PC_ATTACK_DIST_LANCE_TYPE1_LV2_CHARGE = 12
PC_ATTACK_DIST_LANCE_TYPE2_CHARGE = 7.5
PC_ATTACK_DIST_SPIN = 3.57
PC_ATTACK_DIST_JUMP_FRONT = 2.81
PC_ATTACK_DIST_JUMP_BACK = 3.41
PC_ATTACK_DIST_MEN_1 = 4.16
PC_ATTACK_DIST_MEN_2 = 3.59
PC_ATTACK_DIST_KENSEI_IAI = 3.45
PC_ATTACK_DIST_IAI = 4.9
PC_ATTACK_DIST_INVISIBLE_IAI_1 = 6.5
PC_ATTACK_DIST_INVISIBLE_IAI_2 = 6.4
PC_ATTACK_DIST_HASSOU = 4.2
PC_ATTACK_DIST_HUSHIGIRI_LV1 = 3.85
PC_ATTACK_DIST_HUSHIGIRI_LV2 = 6.19
PC_ATTACK_DIST_HUSHIGIRI_LV2_CHARGE = 8.38
PC_ATTACK_DIST_KICK_RUSH = 2.7
PC_ATTACK_DIST_PUNCHI = 3
PC_ATTACK_DIST_GATOTSU = 10.11


AI_NUMBER_LATEST_SOUND_ID = 63
AI_NUMBER_LAST_POINT_ACTION = 62
AI_NUMBER_SEARCH_ENEMY_ACTION = 61
AI_NUMBER_BLOOD_SMOKE_BLINDNESS = 60
-- 最近的动作
AI_NUMBER_LATEST_ACTION = 59

-- 14 号计时器，ai用来连续防御
AI_TIMER_PARRY_INTERVAL = 14
-- 敌人反应？
AI_TIMER_TEKIMAWASHI_REACTION = 15

--[[
    常用 sp 定义，和 param 文件关联
]]
-- ai state 相关
-- 正常
SP_AI_STATE_NORMAL = 200000
-- 非战斗警觉
SP_AI_STATE_NON_COMBAT_VIGILANCE = 200001
-- 战斗警戒
SP_AI_STATE_COMBAT_ALERT = 200002
-- 发现 or 战斗
SP_AI_STATE_DISCOVERY_OR_COMBAT = 200004

-- 死亡
SP_DEAD = 110060
-- 从跌倒中恢复，站起来
SP_RETURN_FROM_FALLING = 120
-- 忍杀
SP_NINSATSU = 110030
-- 复活后 1？一阶段？
SP_REVIVAL_AFTER_1 = 110031
-- 复活后 2？二阶段？
SP_REVIVAL_AFTER_2 = 110032
-- 复活后 3？三阶段？
SP_REVIVAL_AFTER_3 = 110033
-- 蹲伏灌木丛隐身
SP_HIDE_IN_BUSH = 109203
-- 血烟术隐藏
SP_HIDE_IN_BLOOD = 109230
-- pc 崩躯干
SP_PC_BREAK = 110125
-- 连击
SP_CONTINUOUS_ATTACK = 109990
-- 头晕
SP_DIZZINESS = 8300
-- 义手 忍具 转向扇 令敌人转向
SP_ENEMY_TURN = 107710
-- 敌人反应回放 血烟？
SP_BLOOD_SMOKE = 220010
-- 敌人反应回放 爆竹？
SP_FIRE_CRACKER = 220011
-- small fish 声响反应？普通小兵？
SP_ZAKO_REACTION = 241000
-- small fish 声响没反应？
SP_ZAKO_NOREACTION = 241010
-- middle boss sound reaction? 精英？
SP_CHUBOSS_REACTION = 241100
-- middle boss sound no reaction?
SP_CHUBOSS_NOREACTION = 241110
-- boss?
SP_BOSS = 241200
-- 指笛 敌人疯狂
SP_FINGER_WHISTLE_ENEMY_MADNESS = 230515
-- 指笛 敌人疯狂 小调？
SP_FINGER_WHISTLE_ENEMY_MADNESS_MINOR = 230516
-- quick turn at start of conversation?
SP_TURN_AT_START_OF_CONVERSATION = 30600
-- 不要转向巢穴?
SP_NOT_TURN_TO_NEST = 30601
-- 傀儡忍殺?
SP_PUPPET_SHINOBI = 220020
-- 无法中断？
SP_CANT_BE_INTERRUPTED_PERSISTENT = 205050
-- 无法中断？
SP_CANT_BE_INTERRUPTED_MOMENT = 205051
-- 因为被转向，失去对 pc sight 跟踪
SP_LOST_SIGHT_OF_PC_BY_TURNING = 240100
-- 用于招架计数
SP_GUARD_COUNT = 200250
-- 用于弹开计数 右
SP_PARRY_COUNT_RIGHT = 200210
-- 用于弹开计数 左
SP_PARRY_COUNT_LEFT = 200211
-- 不响应声响 永久
SP_NOT_REACT_TO_SOUND_PERSISTENT = 205060
-- 不响应声响 暂时
SP_NOT_REACT_TO_SOUND_MOMENT = 205061




COMMON_OBSERVE_SLOT_BATTLE_STEALTH = 101
COMMON_OBSERVE_SLOT_FINISH_BACKHOME = 102

LATEST_ACTION_NON_BATTLE_GOAL_BATTLE = 1
LATEST_ACTION_NON_BATTLE_GOAL_NON = 2
LATEST_ACTION_BATTLE_GOAL = 3

POSSIBLE_ATTACK = -1
UNREACH_ATTACK = 0

REACH_ATTACK_TARGET_HIGH_POSITION = 1
REACH_ATTACK_TARGET_LOW_POSITION = 2

COMMON_REGION_FORCE_WALK_M11_0 = 1102198
COMMON_REGION_FORCE_WALK_M11_1 = 1112579


-- sound param
-- 陶片 击中其它 非锁定？
SOUND_CERAMIC_HIT = 3500
-- 陶片 击中目标 锁定？
SOUND_CERAMIC_HIT_TARGET = 3501
-- 指笛 非锁定
SOUND_FINGER_WHISTLE_NO_LOCK = 7900
-- 指笛 锁定
SOUND_FINGER_WHISTLE_LOCK_ON_TARGET = 7901
-- 敌人转身？
SOUND_ENEMY_TURN = 7700